import { StockStatus } from '@prisma/client';

/**
 * DEMO products.
 *
 * Every name carries a "(تجريبي)" / "(demo)" suffix, and every price, spec and
 * availability here is a PLACEHOLDER for building against. None of it is MPS's
 * real catalogue or commercial terms. Real products are entered through the
 * admin.
 *
 * The set is deliberately wide rather than deep: three product types with
 * different specification shapes, six brands, four price bands and a mix of
 * availability states, because a catalogue of three near-identical rows cannot
 * show whether filters, sorting, empty states or the grid actually work.
 */

export interface DemoProduct {
  productType: string;
  brand: string;
  category: string;
  slug: string;
  nameAr: string;
  nameEn: string;
  taglineAr: string;
  taglineEn: string;
  image: string;
  warrantyMonths: number;
  isFeatured?: boolean;
  isNewArrival?: boolean;
  isBestSeller?: boolean;
  overviewAr?: string;
  overviewEn?: string;
  prosAr?: string[];
  prosEn?: string[];
  consAr?: string[];
  consEn?: string[];
  whoIsItForAr?: string;
  whoIsItForEn?: string;
  attributes: Record<string, string | number | boolean>;
  options: Array<{
    nameAr: string;
    nameEn: string;
    isColor?: boolean;
    values: Array<{ valueAr: string; valueEn: string; hex?: string }>;
  }>;
  variants: Array<{
    sku: string;
    labelAr: string;
    labelEn: string;
    priceIqd: number;
    comparePriceIqd?: number;
    optionValues: string[];
    status?: StockStatus;
  }>;
  videos?: Array<{ url: string; titleAr: string; titleEn: string }>;
}

// -- Option builders --------------------------------------------------------
// Colour and memory options repeat across most devices. Building them keeps the
// data below readable, so a reviewer can see what differs between products
// instead of scrolling past the same twelve lines seventeen times.

const COLOURS = {
  black: { valueAr: 'أسود', valueEn: 'Black', hex: '#1A1A1D' },
  blue: { valueAr: 'أزرق', valueEn: 'Blue', hex: '#1E3A8A' },
  green: { valueAr: 'أخضر', valueEn: 'Green', hex: '#14532D' },
  silver: { valueAr: 'فضي', valueEn: 'Silver', hex: '#C7C9CC' },
  gold: { valueAr: 'ذهبي', valueEn: 'Gold', hex: '#B8860B' },
  white: { valueAr: 'أبيض', valueEn: 'White', hex: '#F2F2F3' },
  purple: { valueAr: 'بنفسجي', valueEn: 'Purple', hex: '#5B21B6' },
} as const;

type ColourKey = keyof typeof COLOURS;

const colourOption = (...keys: ColourKey[]) => ({
  nameAr: 'اللون',
  nameEn: 'Colour',
  isColor: true,
  values: keys.map((key) => ({ ...COLOURS[key] })),
});

const memoryOption = (combos: Array<[number, number]>) => ({
  nameAr: 'الذاكرة والتخزين',
  nameEn: 'Memory',
  values: combos.map(([ram, storage]) => ({
    valueAr: `${ram} جيجا / ${storage} جيجا`,
    valueEn: `${ram}GB / ${storage}GB`,
  })),
});

export const DEMO_PRODUCTS: DemoProduct[] = [
  // ======================================================== PHONES · BUDGET ==
  {
    productType: 'phone',
    brand: 'tecno',
    category: 'budget',
    slug: 'tecno-spark-30-demo',
    nameAr: 'تكنو سبارك 30 (تجريبي)',
    nameEn: 'TECNO Spark 30 (demo)',
    taglineAr: 'بطارية كبيرة بسعر مناسب',
    taglineEn: 'Big battery, small price',
    image: 'phone-tecno',
    warrantyMonths: 12,
    isBestSeller: true,
    overviewAr:
      'هاتف اقتصادي يركّز على عمر البطارية والاستخدام اليومي البسيط: تصفّح، واتساب، كاميرا مقبولة.',
    overviewEn:
      'A budget phone built around battery life and everyday use: browsing, messaging, a serviceable camera.',
    prosAr: ['بطارية تدوم يومًا كاملًا', 'شاشة كبيرة', 'سعر في المتناول'],
    prosEn: ['All-day battery', 'Large screen', 'Affordable'],
    consAr: ['الكاميرا الليلية متواضعة', 'غير مناسب للألعاب الثقيلة'],
    consEn: ['Weak low-light camera', 'Not for demanding games'],
    whoIsItForAr: 'يناسب الاستخدام اليومي البسيط ومن يريد بطارية تدوم.',
    whoIsItForEn: 'Suits light daily use and anyone who wants battery life first.',
    attributes: {
      display_size_inch: 6.6,
      display_type: 'ips_lcd',
      refresh_rate_hz: 90,
      resolution: '720 x 1612',
      chipset: 'Demo Chip A22',
      chipset_brand: 'unisoc',
      ram_gb: 4,
      storage_gb: 128,
      gaming_ready: false,
      main_camera_mp: 48,
      front_camera_mp: 8,
      battery_mah: 5000,
      charging_watt: 18,
      os: 'android',
      has_5g: false,
      has_nfc: false,
      sim_slots: 2,
      weight_grams: 190,
    },
    options: [
      memoryOption([
        [4, 128],
        [8, 128],
      ]),
      colourOption('black', 'blue'),
    ],
    variants: [
      {
        sku: 'DEMO-TEC-SP30-4-128-BLK',
        labelAr: '4 جيجا / 128 جيجا · أسود',
        labelEn: '4GB / 128GB · Black',
        priceIqd: 215000,
        comparePriceIqd: 240000,
        optionValues: ['4GB / 128GB', 'Black'],
      },
      {
        sku: 'DEMO-TEC-SP30-8-128-BLU',
        labelAr: '8 جيجا / 128 جيجا · أزرق',
        labelEn: '8GB / 128GB · Blue',
        priceIqd: 248000,
        optionValues: ['8GB / 128GB', 'Blue'],
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'infinix',
    category: 'budget',
    slug: 'infinix-hot-60-demo',
    nameAr: 'إنفينكس هوت 60 (تجريبي)',
    nameEn: 'Infinix Hot 60 (demo)',
    taglineAr: 'أساسيات قوية بأقل سعر',
    taglineEn: 'The essentials, for less',
    image: 'phone-infinix',
    warrantyMonths: 12,
    overviewAr: 'خيار اقتصادي لمن يحتاج هاتفًا يشتغل بثبات بدون تعقيد.',
    overviewEn: 'A budget option for anyone who needs a phone that simply works.',
    prosAr: ['سعر منخفض', 'شاشة 120Hz نادرة بهذي الفئة'],
    prosEn: ['Low price', '120Hz screen, rare at this price'],
    consAr: ['ذاكرة تخزين محدودة', 'بدون NFC'],
    consEn: ['Limited storage', 'No NFC'],
    attributes: {
      display_size_inch: 6.7,
      display_type: 'ips_lcd',
      refresh_rate_hz: 120,
      resolution: '720 x 1600',
      chipset: 'Demo Chip G50',
      chipset_brand: 'mediatek',
      ram_gb: 4,
      storage_gb: 128,
      gaming_ready: false,
      main_camera_mp: 50,
      front_camera_mp: 8,
      battery_mah: 5000,
      charging_watt: 18,
      os: 'android',
      has_5g: false,
      has_nfc: false,
      sim_slots: 2,
      weight_grams: 194,
    },
    options: [colourOption('black', 'green')],
    variants: [
      {
        sku: 'DEMO-INF-H60-BLK',
        labelAr: '4 جيجا / 128 جيجا · أسود',
        labelEn: '4GB / 128GB · Black',
        priceIqd: 185000,
        optionValues: ['Black'],
      },
      {
        sku: 'DEMO-INF-H60-GRN',
        labelAr: '4 جيجا / 128 جيجا · أخضر',
        labelEn: '4GB / 128GB · Green',
        priceIqd: 185000,
        optionValues: ['Green'],
        status: StockStatus.OUT_OF_STOCK,
      },
    ],
  },

  // ===================================================== PHONES · MID-RANGE ==
  {
    productType: 'phone',
    brand: 'tecno',
    category: 'mid-range',
    slug: 'tecno-camon-40-demo',
    nameAr: 'تكنو كامون 40 (تجريبي)',
    nameEn: 'TECNO Camon 40 (demo)',
    taglineAr: 'كاميرا قوية وبطارية تدوم',
    taglineEn: 'Strong camera, battery that lasts',
    image: 'phone-tecno',
    warrantyMonths: 12,
    isFeatured: true,
    isNewArrival: true,
    overviewAr:
      'يركّز على التصوير وشاشة AMOLED بمعدل تحديث عالٍ، مع شحن سريع يكفي ليوم كامل.',
    overviewEn:
      'Built around its camera and a high-refresh AMOLED panel, with fast charging that covers a full day.',
    prosAr: ['شاشة AMOLED بمعدل 120Hz', 'شحن سريع 45 واط', 'كاميرا 50 ميجابكسل'],
    prosEn: ['120Hz AMOLED display', '45W fast charging', '50MP main camera'],
    consAr: ['بدون مقاومة ماء معتمدة', 'الصوت أحادي'],
    consEn: ['No rated water resistance', 'Mono speaker'],
    whoIsItForAr: 'يناسب من يصوّر كثيرًا ويريد شاشة سلسة بسعر متوسط.',
    whoIsItForEn: 'For people who shoot a lot and want a smooth screen at a mid price.',
    attributes: {
      display_size_inch: 6.78,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1080 x 2436',
      chipset: 'Demo Chip G99',
      chipset_brand: 'mediatek',
      ram_gb: 8,
      storage_gb: 256,
      gaming_ready: true,
      main_camera_mp: 50,
      front_camera_mp: 32,
      battery_mah: 5000,
      charging_watt: 45,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      weight_grams: 195,
    },
    options: [
      memoryOption([
        [8, 256],
        [12, 256],
      ]),
      colourOption('black', 'blue'),
    ],
    variants: [
      {
        sku: 'DEMO-TEC-C40-8-256-BLK',
        labelAr: '8 جيجا / 256 جيجا · أسود',
        labelEn: '8GB / 256GB · Black',
        priceIqd: 385000,
        comparePriceIqd: 425000,
        optionValues: ['8GB / 256GB', 'Black'],
      },
      {
        sku: 'DEMO-TEC-C40-8-256-BLU',
        labelAr: '8 جيجا / 256 جيجا · أزرق',
        labelEn: '8GB / 256GB · Blue',
        priceIqd: 385000,
        optionValues: ['8GB / 256GB', 'Blue'],
      },
      {
        sku: 'DEMO-TEC-C40-12-256-BLK',
        labelAr: '12 جيجا / 256 جيجا · أسود',
        labelEn: '12GB / 256GB · Black',
        priceIqd: 430000,
        optionValues: ['12GB / 256GB', 'Black'],
        status: StockStatus.OUT_OF_STOCK,
      },
    ],
    videos: [
      {
        // Placeholder id; replaced with a real review link from the admin.
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        titleAr: 'مراجعة الجهاز (رابط تجريبي)',
        titleEn: 'Hands-on review (demo link)',
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'infinix',
    category: 'gaming',
    slug: 'infinix-note-50-demo',
    nameAr: 'إنفينكس نوت 50 (تجريبي)',
    nameEn: 'Infinix Note 50 (demo)',
    taglineAr: 'مبني للألعاب والشحن السريع',
    taglineEn: 'Built for games and fast charging',
    image: 'phone-infinix',
    warrantyMonths: 12,
    isFeatured: true,
    overviewAr:
      'موجّه للألعاب: تبريد أفضل، شاشة سريعة، وشحن 68 واط يملأ البطارية بسرعة.',
    overviewEn:
      'Aimed at gaming: better cooling, a fast panel, and 68W charging that refills quickly.',
    prosAr: ['شحن 68 واط', 'شاشة AMOLED 144Hz', 'ذاكرة 12 جيجا'],
    prosEn: ['68W charging', '144Hz AMOLED', '12GB RAM'],
    consAr: ['ثقيل نسبيًا', 'يسخن مع الجلسات الطويلة'],
    consEn: ['On the heavy side', 'Warms up in long sessions'],
    whoIsItForAr: 'يناسب اللاعبين ومن يشغّل تطبيقات كثيرة بنفس الوقت.',
    whoIsItForEn: 'For gamers and heavy multitaskers.',
    attributes: {
      display_size_inch: 6.78,
      display_type: 'amoled',
      refresh_rate_hz: 144,
      resolution: '1080 x 2436',
      chipset: 'Demo Chip D8200',
      chipset_brand: 'mediatek',
      ram_gb: 12,
      storage_gb: 256,
      gaming_ready: true,
      main_camera_mp: 108,
      front_camera_mp: 32,
      battery_mah: 5200,
      charging_watt: 68,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      weight_grams: 208,
    },
    options: [colourOption('black', 'gold')],
    variants: [
      {
        sku: 'DEMO-INF-N50-BLK',
        labelAr: '12 جيجا / 256 جيجا · أسود',
        labelEn: '12GB / 256GB · Black',
        priceIqd: 340000,
        comparePriceIqd: 380000,
        optionValues: ['Black'],
      },
      {
        sku: 'DEMO-INF-N50-GLD',
        labelAr: '12 جيجا / 256 جيجا · ذهبي',
        labelEn: '12GB / 256GB · Gold',
        priceIqd: 340000,
        optionValues: ['Gold'],
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'realme',
    category: 'mid-range',
    slug: 'realme-14-pro-demo',
    nameAr: 'ريلمي 14 برو (تجريبي)',
    nameEn: 'realme 14 Pro (demo)',
    taglineAr: 'تصميم أنيق وأداء متوازن',
    taglineEn: 'Clean design, balanced performance',
    image: 'phone-realme',
    warrantyMonths: 12,
    isNewArrival: true,
    overviewAr: 'توازن بين التصميم والأداء والكاميرا، بدون تنازل واضح في أي جانب.',
    overviewEn:
      'Balances design, performance and camera without an obvious weak point.',
    prosAr: ['شاشة منحنية', 'شحن 80 واط', 'تصميم خفيف'],
    prosEn: ['Curved display', '80W charging', 'Light in the hand'],
    consAr: ['الشاشة المنحنية تحتاج حافظة مناسبة'],
    consEn: ['Curved screen needs the right case'],
    attributes: {
      display_size_inch: 6.7,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1264 x 2780',
      chipset: 'Demo Chip SD7',
      chipset_brand: 'snapdragon',
      ram_gb: 12,
      storage_gb: 512,
      gaming_ready: true,
      main_camera_mp: 50,
      front_camera_mp: 32,
      battery_mah: 5200,
      charging_watt: 80,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      weight_grams: 183,
    },
    options: [
      memoryOption([
        [8, 256],
        [12, 512],
      ]),
      colourOption('purple', 'white'),
    ],
    variants: [
      {
        sku: 'DEMO-RLM-14P-8-256-PUR',
        labelAr: '8 جيجا / 256 جيجا · بنفسجي',
        labelEn: '8GB / 256GB · Purple',
        priceIqd: 465000,
        optionValues: ['8GB / 256GB', 'Purple'],
      },
      {
        sku: 'DEMO-RLM-14P-12-512-WHT',
        labelAr: '12 جيجا / 512 جيجا · أبيض',
        labelEn: '12GB / 512GB · White',
        priceIqd: 545000,
        comparePriceIqd: 590000,
        optionValues: ['12GB / 512GB', 'White'],
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'honor',
    category: 'mid-range',
    slug: 'honor-x70-demo',
    nameAr: 'هونر X70 (تجريبي)',
    nameEn: 'HONOR X70 (demo)',
    taglineAr: 'بطارية ضخمة تدوم يومين',
    taglineEn: 'A battery that lasts two days',
    image: 'phone-honor',
    warrantyMonths: 12,
    isBestSeller: true,
    overviewAr: 'أكبر بطارية في هذي القائمة، لمن يشتغل خارج البيت طول اليوم.',
    overviewEn: 'The largest battery here, for anyone out of the house all day.',
    prosAr: ['بطارية 6600 مللي أمبير', 'هيكل متين', 'سعر منافس'],
    prosEn: ['6600mAh battery', 'Sturdy build', 'Competitive price'],
    consAr: ['الكاميرا الأمامية عادية'],
    consEn: ['Ordinary front camera'],
    attributes: {
      display_size_inch: 6.8,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1080 x 2412',
      chipset: 'Demo Chip SD6',
      chipset_brand: 'snapdragon',
      ram_gb: 8,
      storage_gb: 256,
      gaming_ready: false,
      main_camera_mp: 108,
      front_camera_mp: 16,
      battery_mah: 6600,
      charging_watt: 35,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      weight_grams: 199,
    },
    options: [colourOption('black', 'silver')],
    variants: [
      {
        sku: 'DEMO-HON-X70-BLK',
        labelAr: '8 جيجا / 256 جيجا · أسود',
        labelEn: '8GB / 256GB · Black',
        priceIqd: 395000,
        optionValues: ['Black'],
      },
      {
        sku: 'DEMO-HON-X70-SLV',
        labelAr: '8 جيجا / 256 جيجا · فضي',
        labelEn: '8GB / 256GB · Silver',
        priceIqd: 395000,
        optionValues: ['Silver'],
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'xiaomi',
    category: 'mid-range',
    slug: 'xiaomi-redmi-note-15-pro-demo',
    nameAr: 'شاومي ريدمي نوت 15 برو (تجريبي)',
    nameEn: 'Xiaomi Redmi Note 15 Pro (demo)',
    taglineAr: 'الخيار المتوازن الأشهر',
    taglineEn: 'The popular all-rounder',
    image: 'phone-xiaomi',
    warrantyMonths: 12,
    isBestSeller: true,
    isFeatured: true,
    overviewAr: 'الخيار الافتراضي لأغلب المشترين: أداء جيد، شاشة ممتازة، وسعر معقول.',
    overviewEn:
      'The default pick for most buyers: good performance, excellent screen, fair price.',
    prosAr: ['شاشة ساطعة جدًا', 'مقاومة ماء IP68', 'تحديثات طويلة'],
    prosEn: ['Very bright display', 'IP68 water resistance', 'Long update support'],
    consAr: ['واجهة فيها تطبيقات زائدة'],
    consEn: ['Interface ships with extra apps'],
    whoIsItForAr: 'يناسب أغلب الناس: استخدام يومي، تصوير، وألعاب متوسطة.',
    whoIsItForEn: 'Suits most people: daily use, photos, moderate gaming.',
    attributes: {
      display_size_inch: 6.67,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1220 x 2712',
      chipset: 'Demo Chip SD7s',
      chipset_brand: 'snapdragon',
      ram_gb: 8,
      storage_gb: 256,
      gaming_ready: true,
      main_camera_mp: 200,
      front_camera_mp: 20,
      battery_mah: 5500,
      charging_watt: 45,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      water_resistance: 'IP68',
      weight_grams: 204,
    },
    options: [
      memoryOption([
        [8, 256],
        [12, 512],
      ]),
      colourOption('black', 'blue', 'purple'),
    ],
    variants: [
      {
        sku: 'DEMO-XMI-RN15P-8-256-BLK',
        labelAr: '8 جيجا / 256 جيجا · أسود',
        labelEn: '8GB / 256GB · Black',
        priceIqd: 375000,
        comparePriceIqd: 410000,
        optionValues: ['8GB / 256GB', 'Black'],
      },
      {
        sku: 'DEMO-XMI-RN15P-8-256-BLU',
        labelAr: '8 جيجا / 256 جيجا · أزرق',
        labelEn: '8GB / 256GB · Blue',
        priceIqd: 375000,
        optionValues: ['8GB / 256GB', 'Blue'],
      },
      {
        sku: 'DEMO-XMI-RN15P-12-512-PUR',
        labelAr: '12 جيجا / 512 جيجا · بنفسجي',
        labelEn: '12GB / 512GB · Purple',
        priceIqd: 448000,
        optionValues: ['12GB / 512GB', 'Purple'],
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'samsung',
    category: 'mid-range',
    slug: 'samsung-galaxy-a36-demo',
    nameAr: 'سامسونج جالكسي A36 (تجريبي)',
    nameEn: 'Samsung Galaxy A36 (demo)',
    taglineAr: 'سامسونج بسعر متوسط',
    taglineEn: 'Samsung at a mid price',
    image: 'phone-samsung',
    warrantyMonths: 12,
    overviewAr: 'يوفّر تجربة سامسونج وتحديثاتها الطويلة بسعر أقل من الفئة الرائدة.',
    overviewEn: "Samsung's software and long update policy, below flagship money.",
    prosAr: ['تحديثات لسنوات', 'شاشة Super AMOLED', 'مقاومة ماء'],
    prosEn: ['Years of updates', 'Super AMOLED screen', 'Water resistant'],
    consAr: ['الشحن أبطأ من المنافسين'],
    consEn: ['Charges slower than rivals'],
    attributes: {
      display_size_inch: 6.7,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1080 x 2340',
      chipset: 'Demo Chip Ex1480',
      chipset_brand: 'exynos',
      ram_gb: 8,
      storage_gb: 256,
      gaming_ready: false,
      main_camera_mp: 50,
      front_camera_mp: 12,
      battery_mah: 5000,
      charging_watt: 25,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      water_resistance: 'IP67',
      weight_grams: 196,
    },
    options: [colourOption('black', 'white', 'purple')],
    variants: [
      {
        sku: 'DEMO-SAM-A36-BLK',
        labelAr: '8 جيجا / 256 جيجا · أسود',
        labelEn: '8GB / 256GB · Black',
        priceIqd: 520000,
        optionValues: ['Black'],
      },
      {
        sku: 'DEMO-SAM-A36-WHT',
        labelAr: '8 جيجا / 256 جيجا · أبيض',
        labelEn: '8GB / 256GB · White',
        priceIqd: 520000,
        optionValues: ['White'],
      },
    ],
  },

  // ====================================================== PHONES · FLAGSHIP ==
  {
    productType: 'phone',
    brand: 'samsung',
    category: 'flagship',
    slug: 'samsung-galaxy-s30-ultra-demo',
    nameAr: 'سامسونج جالكسي S30 ألترا (تجريبي)',
    nameEn: 'Samsung Galaxy S30 Ultra (demo)',
    taglineAr: 'أقصى ما تقدمه سامسونج',
    taglineEn: "Samsung's best, without compromise",
    image: 'phone-samsung',
    warrantyMonths: 12,
    isFeatured: true,
    overviewAr: 'الفئة الرائدة بكل معنى الكلمة: كاميرا، أداء، شاشة، وقلم مدمج.',
    overviewEn:
      'A flagship in every sense: camera, performance, display, built-in stylus.',
    prosAr: ['كاميرا تصل 200 ميجابكسل', 'قلم مدمج', 'أداء من الطبقة الأولى'],
    prosEn: ['Up to 200MP camera', 'Built-in stylus', 'Top-tier performance'],
    consAr: ['سعر مرتفع', 'حجم كبير على اليد الصغيرة'],
    consEn: ['Expensive', 'Large for small hands'],
    whoIsItForAr: 'يناسب من يريد الأفضل بدون تنازلات ومستعد لسعره.',
    whoIsItForEn: 'For someone who wants the best and will pay for it.',
    attributes: {
      display_size_inch: 6.9,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1440 x 3120',
      chipset: 'Demo Chip SD8E',
      chipset_brand: 'snapdragon',
      ram_gb: 12,
      storage_gb: 512,
      gaming_ready: true,
      main_camera_mp: 200,
      front_camera_mp: 12,
      battery_mah: 5000,
      charging_watt: 45,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      water_resistance: 'IP68',
      weight_grams: 218,
    },
    options: [
      memoryOption([
        [12, 512],
        [16, 1024],
      ]),
      colourOption('black', 'silver'),
    ],
    variants: [
      {
        sku: 'DEMO-SAM-S30U-12-512-BLK',
        labelAr: '12 جيجا / 512 جيجا · أسود',
        labelEn: '12GB / 512GB · Black',
        priceIqd: 1650000,
        comparePriceIqd: 1790000,
        optionValues: ['12GB / 512GB', 'Black'],
      },
      {
        sku: 'DEMO-SAM-S30U-16-1024-SLV',
        labelAr: '16 جيجا / 1 تيرا · فضي',
        labelEn: '16GB / 1TB · Silver',
        priceIqd: 1980000,
        optionValues: ['16GB / 1024GB', 'Silver'],
      },
    ],
  },
  {
    productType: 'phone',
    brand: 'xiaomi',
    category: 'flagship',
    slug: 'xiaomi-16-pro-demo',
    nameAr: 'شاومي 16 برو (تجريبي)',
    nameEn: 'Xiaomi 16 Pro (demo)',
    taglineAr: 'كاميرا رائدة وشحن خارق',
    taglineEn: 'Flagship camera, extreme charging',
    image: 'phone-xiaomi',
    warrantyMonths: 12,
    isNewArrival: true,
    overviewAr: 'يركّز على التصوير وسرعة الشحن، مع أداء من الفئة العليا.',
    overviewEn: 'Focused on photography and charging speed, with top-tier performance.',
    prosAr: ['شحن 120 واط', 'عدسات متعددة', 'شاشة عالية الدقة'],
    prosEn: ['120W charging', 'Multiple lenses', 'High-resolution display'],
    consAr: ['يسخن عند الشحن السريع', 'زجاج ظهري يمسك البصمات'],
    consEn: ['Warms during fast charging', 'Glass back shows fingerprints'],
    attributes: {
      display_size_inch: 6.73,
      display_type: 'amoled',
      refresh_rate_hz: 120,
      resolution: '1440 x 3200',
      chipset: 'Demo Chip SD8E',
      chipset_brand: 'snapdragon',
      ram_gb: 12,
      storage_gb: 512,
      gaming_ready: true,
      main_camera_mp: 50,
      front_camera_mp: 32,
      battery_mah: 5400,
      charging_watt: 120,
      os: 'android',
      has_5g: true,
      has_nfc: true,
      sim_slots: 2,
      water_resistance: 'IP68',
      weight_grams: 213,
    },
    options: [colourOption('black', 'green')],
    variants: [
      {
        sku: 'DEMO-XMI-16P-BLK',
        labelAr: '12 جيجا / 512 جيجا · أسود',
        labelEn: '12GB / 512GB · Black',
        priceIqd: 1250000,
        optionValues: ['Black'],
      },
      {
        sku: 'DEMO-XMI-16P-GRN',
        labelAr: '12 جيجا / 512 جيجا · أخضر',
        labelEn: '12GB / 512GB · Green',
        priceIqd: 1250000,
        optionValues: ['Green'],
        status: StockStatus.PREORDER,
      },
    ],
  },

  // ================================================================ TABLETS ==
  {
    productType: 'tablet',
    brand: 'samsung',
    category: 'phones',
    slug: 'samsung-tab-s10-demo',
    nameAr: 'سامسونج تاب S10 (تجريبي)',
    nameEn: 'Samsung Tab S10 (demo)',
    taglineAr: 'شاشة كبيرة ودعم القلم',
    taglineEn: 'Big screen with stylus support',
    image: 'tablet-samsung',
    warrantyMonths: 12,
    isFeatured: true,
    overviewAr: 'جهاز لوحي للدراسة والعمل والمشاهدة، مع دعم القلم للملاحظات.',
    overviewEn: 'A tablet for study, work and watching, with stylus support for notes.',
    prosAr: ['شاشة 11 إنش', 'يدعم القلم', 'بطارية كبيرة'],
    prosEn: ['11-inch screen', 'Stylus support', 'Large battery'],
    consAr: ['نسخة الواي فاي بدون شريحة اتصال'],
    consEn: ['Wi-Fi model has no cellular'],
    attributes: {
      display_size_inch: 11,
      display_type: 'ips_lcd',
      refresh_rate_hz: 90,
      resolution: '1600 x 2560',
      chipset: 'Demo Tablet Chip',
      chipset_brand: 'snapdragon',
      ram_gb: 8,
      storage_gb: 128,
      main_camera_mp: 13,
      front_camera_mp: 12,
      battery_mah: 8000,
      charging_watt: 45,
      os: 'android',
      cellular: false,
      stylus_support: true,
      weight_grams: 498,
    },
    options: [
      {
        nameAr: 'الاتصال',
        nameEn: 'Connectivity',
        values: [
          { valueAr: 'واي فاي', valueEn: 'Wi-Fi' },
          { valueAr: 'واي فاي + شريحة', valueEn: 'Wi-Fi + Cellular' },
        ],
      },
    ],
    variants: [
      {
        sku: 'DEMO-TAB-S10-WIFI',
        labelAr: 'واي فاي · 128 جيجا',
        labelEn: 'Wi-Fi · 128GB',
        priceIqd: 620000,
        optionValues: ['Wi-Fi'],
      },
      {
        sku: 'DEMO-TAB-S10-LTE',
        labelAr: 'واي فاي + شريحة · 128 جيجا',
        labelEn: 'Wi-Fi + Cellular · 128GB',
        priceIqd: 745000,
        optionValues: ['Wi-Fi + Cellular'],
      },
    ],
  },
  {
    productType: 'tablet',
    brand: 'xiaomi',
    category: 'phones',
    slug: 'xiaomi-pad-8-demo',
    nameAr: 'شاومي باد 8 (تجريبي)',
    nameEn: 'Xiaomi Pad 8 (demo)',
    taglineAr: 'شاشة 144Hz للترفيه',
    taglineEn: '144Hz screen for entertainment',
    image: 'tablet-xiaomi',
    warrantyMonths: 12,
    isNewArrival: true,
    overviewAr: 'جهاز لوحي بشاشة سريعة وصوت رباعي، مناسب للمشاهدة والألعاب.',
    overviewEn:
      'A tablet with a fast panel and quad speakers, suited to watching and games.',
    prosAr: ['شاشة 144Hz', 'صوت رباعي', 'خفيف'],
    prosEn: ['144Hz display', 'Quad speakers', 'Light'],
    consAr: ['بدون نسخة شريحة اتصال'],
    consEn: ['No cellular variant'],
    attributes: {
      display_size_inch: 11.2,
      display_type: 'ips_lcd',
      refresh_rate_hz: 144,
      resolution: '1800 x 2880',
      chipset: 'Demo Chip SD8s',
      chipset_brand: 'snapdragon',
      ram_gb: 8,
      storage_gb: 256,
      main_camera_mp: 13,
      front_camera_mp: 8,
      battery_mah: 8850,
      charging_watt: 67,
      os: 'android',
      cellular: false,
      stylus_support: true,
      weight_grams: 490,
    },
    options: [colourOption('silver', 'blue')],
    variants: [
      {
        sku: 'DEMO-XMI-PAD8-SLV',
        labelAr: '8 جيجا / 256 جيجا · فضي',
        labelEn: '8GB / 256GB · Silver',
        priceIqd: 480000,
        comparePriceIqd: 530000,
        optionValues: ['Silver'],
      },
      {
        sku: 'DEMO-XMI-PAD8-BLU',
        labelAr: '8 جيجا / 256 جيجا · أزرق',
        labelEn: '8GB / 256GB · Blue',
        priceIqd: 480000,
        optionValues: ['Blue'],
      },
    ],
  },

  // ============================================================ ACCESSORIES ==
  {
    productType: 'accessory',
    brand: 'xiaomi',
    category: 'accessories',
    slug: 'xiaomi-power-bank-20000-demo',
    nameAr: 'باور بانك شاومي 20000 (تجريبي)',
    nameEn: 'Xiaomi Power Bank 20000 (demo)',
    taglineAr: 'شحن سريع لجهازين معًا',
    taglineEn: 'Fast charging for two devices',
    image: 'accessory-xiaomi',
    warrantyMonths: 6,
    isBestSeller: true,
    overviewAr: 'بطارية محمولة تكفي لشحن هاتف عادي أكثر من ثلاث مرات.',
    overviewEn: 'A power bank that refills a typical phone more than three times.',
    prosAr: ['منفذان في نفس الوقت', 'شحن سريع 22 واط'],
    prosEn: ['Two ports at once', '22W fast charging'],
    consAr: ['ثقيل نسبيًا للجيب'],
    consEn: ['Heavy for a pocket'],
    attributes: {
      accessory_kind: 'power_bank',
      compatible_with: 'USB-C / Lightning',
      capacity_mah: 20000,
      charging_watt: 22,
      wireless: false,
      weight_grams: 440,
    },
    options: [colourOption('black', 'white')],
    variants: [
      {
        sku: 'DEMO-ACC-PB20-BLK',
        labelAr: 'أسود',
        labelEn: 'Black',
        priceIqd: 38000,
        comparePriceIqd: 45000,
        optionValues: ['Black'],
      },
      {
        sku: 'DEMO-ACC-PB20-WHT',
        labelAr: 'أبيض',
        labelEn: 'White',
        priceIqd: 38000,
        optionValues: ['White'],
      },
    ],
  },
  {
    productType: 'accessory',
    brand: 'samsung',
    category: 'accessories',
    slug: 'samsung-charger-45w-demo',
    nameAr: 'شاحن سامسونج 45 واط (تجريبي)',
    nameEn: 'Samsung 45W Charger (demo)',
    taglineAr: 'شحن سريع بكيبل مرفق',
    taglineEn: 'Fast charging, cable included',
    image: 'accessory-samsung',
    warrantyMonths: 6,
    overviewAr: 'شاحن أصلي بقوة 45 واط، يدعم معايير الشحن السريع الشائعة.',
    overviewEn: 'A 45W charger supporting the common fast-charging standards.',
    prosAr: ['كيبل مرفق', 'حجم صغير'],
    prosEn: ['Cable included', 'Compact'],
    consAr: ['منفذ واحد فقط'],
    consEn: ['Single port'],
    attributes: {
      accessory_kind: 'charger',
      compatible_with: 'USB-C PD / PPS',
      charging_watt: 45,
      wireless: false,
      weight_grams: 62,
    },
    options: [colourOption('white', 'black')],
    variants: [
      {
        sku: 'DEMO-ACC-CH45-WHT',
        labelAr: 'أبيض',
        labelEn: 'White',
        priceIqd: 32000,
        optionValues: ['White'],
      },
      {
        sku: 'DEMO-ACC-CH45-BLK',
        labelAr: 'أسود',
        labelEn: 'Black',
        priceIqd: 32000,
        optionValues: ['Black'],
      },
    ],
  },
  {
    productType: 'accessory',
    brand: 'honor',
    category: 'accessories',
    slug: 'honor-usb-c-cable-demo',
    nameAr: 'كيبل هونر USB-C (تجريبي)',
    nameEn: 'HONOR USB-C Cable (demo)',
    taglineAr: 'كيبل متين يتحمل الاستخدام اليومي',
    taglineEn: 'A braided cable for daily use',
    image: 'accessory-honor',
    warrantyMonths: 3,
    overviewAr: 'كيبل مجدول بطول متر، يدعم الشحن السريع ونقل البيانات.',
    overviewEn: 'A one-metre braided cable supporting fast charge and data.',
    prosAr: ['مجدول ومتين', 'سعر منخفض'],
    prosEn: ['Braided and durable', 'Low price'],
    consAr: ['طول واحد فقط متوفر حاليًا'],
    consEn: ['Only one length available right now'],
    attributes: {
      accessory_kind: 'cable',
      compatible_with: 'USB-C',
      charging_watt: 100,
      wireless: false,
      weight_grams: 44,
    },
    options: [
      {
        nameAr: 'الطول',
        nameEn: 'Length',
        values: [
          { valueAr: '1 متر', valueEn: '1m' },
          { valueAr: '2 متر', valueEn: '2m' },
        ],
      },
    ],
    variants: [
      {
        sku: 'DEMO-ACC-CBL-1M',
        labelAr: '1 متر',
        labelEn: '1m',
        priceIqd: 12000,
        optionValues: ['1m'],
      },
      {
        sku: 'DEMO-ACC-CBL-2M',
        labelAr: '2 متر',
        labelEn: '2m',
        priceIqd: 16000,
        optionValues: ['2m'],
        status: StockStatus.OUT_OF_STOCK,
      },
    ],
  },
  {
    productType: 'accessory',
    brand: 'realme',
    category: 'accessories',
    slug: 'realme-buds-air-demo',
    nameAr: 'سماعات ريلمي باد إير (تجريبي)',
    nameEn: 'realme Buds Air (demo)',
    taglineAr: 'عزل ضوضاء وبطارية طويلة',
    taglineEn: 'Noise cancelling, long battery',
    image: 'accessory-realme',
    warrantyMonths: 6,
    isNewArrival: true,
    overviewAr: 'سماعات لاسلكية بعزل ضوضاء نشط، مناسبة للتنقل والمكالمات.',
    overviewEn:
      'Wireless earbuds with active noise cancelling, for commuting and calls.',
    prosAr: ['عزل ضوضاء نشط', 'علبة شحن سريعة'],
    prosEn: ['Active noise cancelling', 'Fast-charging case'],
    consAr: ['العزل أقل من السماعات الأغلى'],
    consEn: ['Cancelling is weaker than pricier sets'],
    attributes: {
      accessory_kind: 'earbuds',
      compatible_with: 'Bluetooth 5.3',
      capacity_mah: 400,
      charging_watt: 5,
      wireless: true,
      weight_grams: 42,
    },
    options: [colourOption('white', 'black')],
    variants: [
      {
        sku: 'DEMO-ACC-BUDS-WHT',
        labelAr: 'أبيض',
        labelEn: 'White',
        priceIqd: 68000,
        comparePriceIqd: 79000,
        optionValues: ['White'],
      },
      {
        sku: 'DEMO-ACC-BUDS-BLK',
        labelAr: 'أسود',
        labelEn: 'Black',
        priceIqd: 68000,
        optionValues: ['Black'],
      },
    ],
  },
];
